root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server/"
  bin = "./tmp/server"
  delay = 1000
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp", "node_modules"]

[misc]
  clean_on_exit = true
