name: Create Release Branch

on:
  workflow_dispatch:

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/create-github-app-token@v3
        id: get-installation-token
        with:
          client-id: Iv23licFqbWsDrBD8hcw
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create and push release branch
        env:
          GH_TOKEN: ${{ steps.get-installation-token.outputs.token }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          BRANCH="release/$(date +'%y%m%d')"
          git checkout -b "$BRANCH"
          git push "https://x-access-token:${GH_TOKE}@github.com/${{ github.repository }}" "$BRANCH"
